###
## Configuration
###

### Assets
sass:
  sass_dir: _sass # change this PATH if you want to place your Sass files in a different directory
  style: :nested # look at Jekyll docs for more information; this setting is useful for minifying CSS a bit
